[build]
  # Build command to run
  command = "npm run build:ui:static"
  
  # Directory to publish (must match Angular output directory)
  publish = "dist/apps/ui/browser"
  
  # Install command
  [build.processing]
  skip_processing = false
  
  # Environment variables
  [build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8"

# SPA fallback - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Optional: Health check endpoint for monitoring
[[redirects]]
  from = "/health"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets for 1 year
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache JS and CSS for 1 year (with content hashing)
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"